import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className={styles.bodyWrapper}>
          <header className={styles.header}>
            <div className={styles.navContainer}>
              <div className={styles.logoWrapper}>
                <span className={styles.logoText}>This is my logo</span>
                <span className={styles.logoSubtext}>We r the champion</span>
              </div>
              <nav className={styles.nav}>
                <Link href="/" className={styles.navLink}>
                  Home
                </Link>
                <Link href="/products" className={styles.navLink}>
                  Products
                </Link>
                <Link href="/dashboard" className={styles.navLink}>
                  Posts
                </Link>
                <Link href="/users" className={styles.navLink}>
                  Users
                </Link>
                <Link href="/about" className={styles.navLink}>
                  About
                </Link>
              </nav>
            </div>
          </header>

          <main className={styles.main}>{children}</main>

          <footer className={styles.footer}>
            <p> 2026&copy; CoCamp. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
